[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements-web.txt"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT orc.web.app_new:app"
